name: Build Native

on:
  workflow_run:
    workflows: ["Test"]
    branches: [master]
    types:
      - completed

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Make Gradle executable and prepare env
        run: chmod u+x ./gradlew && sudo apt-get install -y gcc-multilib
      - name: Build with Gradle
        run: ./gradlew clean nativeImage
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: latc_x86
          path: latc_x86
      - name: Release build artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            latc_x86
            lib/runtime.o

  buildWindows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          version: latest
          platform: i686
      - uses: ilammy/msvc-dev-cmd@v1.5.0
      - uses: microsoft/setup-msbuild@v1
      - name: Build with Gradle
        run: ./gradlew.bat clean nativeImage
        shell: powershell
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: latc_x86
          path: latc_x86
